[project]
name = "docs"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-git-revision-date-localized-plugin>=1.4.7",
    "mkdocs-macros-plugin>=1.4.0",
    "mkdocs-material>=9.6.22",
]
